version: '3'
services:

  proxy:
    build: proxy
    container_name: proxy
    expose: 
      - 9000
    restart: always

  add:
    build: add
    container_name: add
    expose:
      - 80
    restart: always

  mul:
    build: mul
    container_name: mul
    expose:
      - 8085
    restart: always

  fe:
    build: fe
    container_name: fe
    ports:
      - 80:80
    restart: always

  # div:
  #   image: "cde"

  # sub:
  #   image: "bda"
